### ISSUE TITLE
Publish prebuild Docker image for GitHub Action

### ISSUE THREAD

**Issue by szapp** [kirides/vdfsbuilder#2]
When using the vdfsbuilder in a GitHub workflow, I've seen the following:

```yml
- name: Package VDF
  working-directory: ${{env.GITHUB_WORKSPACE}}
    run: |
      curl -L --output ./vdfsbuilder https://github.com/kirides/vdfsbuilder/releases/download/v1.0.4/vdfsbuilder.linux-amd64
      chmod +x ./vdfsbuilder
      ./vdfsbuilder -o "${{ env.RELEASE_FILE }}" "${{ env.BUILD_SCRIPT }}"
```
[Source](https://github.com/kirides/gothic-twitch-actions/blob/129d1ea8e9b16778657e70a831035f661e0d1d00/.github/workflows/release-linux.yml#L31C1-L36C79)

But as I see, the repository serves an `action.yml` for usage as GitHub Action, which seems more convenient, less error prone (on user side), and simpler in terms of writing workflow files.

```yml
- uses: kirides/vdfsbuilder@main  # or rather @v1.0.5
  with:
    in: example.vm
```

However, the usage as GitHub Action rebuilds the Docker image every time. 

```
Build container for action use: '/home/runner/work/_actions/kirides/vdfsbuilder/main/Dockerfile'.
  /usr/bin/docker build -t 94f4c6:76f712c74d13400ea86ab8dedc9931be -f "/home/runner/work/_actions/kirides/vdfsbuilder/main/Dockerfile" "/home/runner/work/_actions/kirides/vdfsbuilder/main"
  #0 building with "default" instance using docker driver
  
  #1 [internal] load .dockerignore
  #1 transferring context: 2B done
  #1 DONE 0.0s
 
  --- snip ---

  #13 [stage-1 1/1] COPY --from=builder /bin/action /bin/action
  #13 DONE 0.0s
  
  #14 exporting to image
  #14 exporting layers 0.0s done
  #14 writing image sha256:3b4386b8ee6744a560bedda0ba69ac62cfa592b2e2ac9eef6d8e34a6a0dc1c22 done
  #14 naming to docker.io/library/94f4c6:76f712c74d13400ea86ab8dedc9931be done
  #14 DONE 0.0s
```

This seems to be solveable by specifying a prebuild docker image in the `action.yml` instead of the local Dockerfile, see [here](https://stackoverflow.com/questions/60675844/#60679692).

---

Would you consider publishing an image of your Dockerfile to make the vdfsbuilder usable via GitHub Actions?

---

The reason I am asking for this is that currently I see only marginal advantage for usage inside a GitHub workflow when downloading and running the compiled vdfsbuilder instance, instead of downloading and running GothicVDFS.

**Comment by kirides** [comment]
Sounds like a great idea, didn't have the time initially to get into the guts of github actions with prebuilt images.

Will check the linked documentation out

**Comment by szapp** [comment]
Great to hear! Just FYI, the GitHub Action of the vdfsbuilder already works in its current state. It seems that only the Docker image might be missing.

**Comment by kirides** [comment]
@szapp there now is a pre-built docker image for the action

https://github.com/kirides/vdfsbuilder/pkgs/container/vdfsbuilder

you could try to use it

```yml

env:
  BUILD_SCRIPT: ManaReg.vm
  RELEASE_FILE: ManaReg.vdf

jobs:
  build:
    - uses: kirides/vdfsbuilder@f7438d978d2974f9c1e97fd6dd3419709795c9d2
      with:
        in: ${{ github.workspace }}/${{ env.BUILD_SCRIPT }}
        out: ${{ github.workspace }}/${{ env.RELEASE_FILE }}
        baseDir: ${{ github.workspace }}
```

**Comment by szapp** [comment]
Thanks! I gave it a quick try. It seems like the image is not reachable. Is it maybe set to private or similar? (I am not familiar with Docker images and packaging.)

```
Pull down action image 'ghcr.io/kirides/vdfsbuilder:v1.0.7'
  /usr/bin/docker pull ghcr.io/kirides/vdfsbuilder:v1.0.7
  Error response from daemon: Head "https://ghcr.io/v2/kirides/vdfsbuilder/manifests/v1.0.7": unauthorized
  Warning: Docker pull failed with exit code 1, back off 6.747 seconds before retry.
Error: Docker pull failed with exit code 1
```

**Comment by kirides** [comment]
Yep the package was indeed private.

I've set it to public, should be working now.

**Comment by szapp** [comment]
Works great!

I noticed that explicitly specifying the github workspace directory doesn't seem to be necessary. The following worked for me:

```yml
- uses: kirides/vdfsbuilder@f7438d978d2974f9c1e97fd6dd3419709795c9d2
  with:
    in: example.vm
```

Thanks for putting in the work. Feel free to close!
